language: php

php:
  - 5.5
  - 5.6
  - 7.0

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
  - vendor/codeception/codeception/codecept build

addons:
  sauce_connect:
    username: "ivansal"
    access_key: "c463c760-f7fa-49db-ba4a-21f42f183e2d"

before_script:
  - mysql -e 'create database yii2_mediastorage_test;'
  - php tests/testapp/yii migrate --interactive=0
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      CODECEPT_FLAGS=" --coverage --coverage-xml"
    fi
script:
  - php tests/testapp/yii serve/index > /dev/null 2>&1 &
  - vendor/codeception/codeception/codecept run --verbose $CODECEPT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      bash <(curl -s https://codecov.io/bash)
    fi